services:
  tinymq:
    build: .
    image: tinymq:latest
    container_name: tinymq
    env_file:
      - .env
    ports:
      - "${PORT:-7800}:7800"
      - "${TINYMQ_MQTT_PORT:-1883}:${TINYMQ_MQTT_PORT:-1883}"
      - "${TINYMQ_CLUSTER_ADDR_PORT:-7901}:7901"
      - "${TINYMQ_NATS_PORT:-4222}:${TINYMQ_NATS_PORT:-4222}"
    volumes:
      - ./data:/home/tinymq/data
    restart: unless-stopped
    user: "10001:10001"