services:
  tinymq:
    build: .
    image: tinymq:latest
    env_file:
      - .env
    ports:
      - "${PORT:-7800}:7800" 
      - "${TINYMQ_MQTT_PORT:-1883}:${TINYMQ_MQTT_PORT:-1883}"
    volumes:
      - ./data:/home/tinymq/data
    restart: unless-stopped